// components/CameraCard.vue
<template>
  <div class="bg-card border rounded-lg p-3 hover:shadow-md transition-shadow">
    <div class="flex items-center justify-between mb-2">
      <div class="flex items-center gap-2">
        <div :class="`h-2 w-2 rounded-full ${getConnectionStatusColor(camera.connectionStatus)}`"></div>
        <span class="text-sm font-medium">{{ camera.label }}</span>
      </div>
      <Badge :variant="getStreamStatusVariant(camera.streamStatus)" class="text-xs">
        {{ camera.streamStatus }}
      </Badge>
    </div>
    
    <div class="relative mb-3">
      <img
        :src="camera.thumbnailUrl"
        :alt="camera.name"
        class="w-full h-24 object-cover rounded border"
      />
      <div v-if="camera.isTriggerActive" class="absolute top-1 right-1">
        <div class="bg-green-500 text-white rounded-full p-1">
          <Zap class="h-3 w-3" />
        </div>
      </div>
    </div>
    
    <div class="space-y-1 text-xs text-muted-foreground mb-3">
      <div>{{ camera.name }}</div>
      <div>Zone: {{ camera.zone }}</div>
    </div>
    
    <Button
      size="sm"
      variant="outline"
      class="w-full"
      @click="$emit('take-snapshot', camera.id)"
    >
      <Camera class="h-3 w-3 mr-1" />
      Snapshot
    </Button>
  </div>
</template>

<script setup>
import Button from './ui/Button.vue'
import Badge from './ui/Badge.vue'
import { Camera, Zap } from 'lucide-vue-next'

defineProps({
  camera: {
    type: Object,
    required: true
  }
})

defineEmits(['take-snapshot'])

const getConnectionStatusColor = (status) => {
  switch (status) {
    case 'connected':
      return 'bg-green-500'
    case 'warning':
      return 'bg-yellow-500'
    case 'disconnected':
      return 'bg-red-500'
    default:
      return 'bg-gray-500'
  }
}

const getStreamStatusVariant = (status) => {
  switch (status) {
    case 'streaming':
      return 'default'
    case 'idle':
      return 'secondary'
    case 'error':
      return 'destructive'
    default:
      return 'outline'
  }
}
</script>

// components/line-check/camera-card.tsx
"use client"

import type React from "react"

import Image from "next/image"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { CheckCircle, XCircle, AlertTriangle, WifiOff, Video, VideoOff, CameraIcon, Zap, PowerOff } from "lucide-react"
import type { CameraType } from "./line-check-dashboard" // Assuming type is exported

interface CameraCardProps {
  camera: CameraType
  onTakeSnapshot: (cameraId: string) => void
}

const CameraCard: React.FC<CameraCardProps> = ({ camera, onTakeSnapshot }) => {
  let connectionIcon, streamIcon
  let connectionColorClass = "text-muted-foreground"
  let streamColorClass = "text-muted-foreground"

  switch (camera.connectionStatus) {
    case "connected":
      connectionIcon = <CheckCircle className="w-4 h-4" />
      connectionColorClass = "text-green-600"
      break
    case "disconnected":
      connectionIcon = <XCircle className="w-4 h-4" />
      connectionColorClass = "text-red-600"
      break
    case "warning":
      connectionIcon = <AlertTriangle className="w-4 h-4" />
      connectionColorClass = "text-yellow-600"
      break
    default:
      connectionIcon = <WifiOff className="w-4 h-4" />
  }

  switch (camera.streamStatus) {
    case "streaming":
      streamIcon = <Video className="w-4 h-4" />
      streamColorClass = "text-blue-600"
      break
    case "idle":
      streamIcon = <PowerOff className="w-4 h-4" /> // Using PowerOff for idle
      streamColorClass = "text-gray-500"
      break
    case "error":
      streamIcon = <VideoOff className="w-4 h-4" />
      streamColorClass = "text-orange-600"
      break
    case "no_signal":
      streamIcon = <VideoOff className="w-4 h-4" />
      streamColorClass = "text-red-500" // More prominent for no signal
      break
    default:
      streamIcon = <VideoOff className="w-4 h-4" />
  }

  return (
    <Card className="flex flex-col h-full">
      <CardHeader className="p-3">
        <div className="relative w-full aspect-video rounded overflow-hidden mb-2">
          <Image
            src={camera.thumbnailUrl || "/placeholder.svg?width=160&height=120&query=camera_feed"}
            alt={`Preview for ${camera.name}`}
            layout="fill"
            objectFit="cover"
            className="bg-muted"
          />
          {camera.isTriggerActive && (
            <Badge className="absolute top-1 right-1 bg-purple-100 text-purple-800 text-xs px-1.5 py-0.5">
              <Zap className="w-3 h-3 mr-1" /> Trigger
            </Badge>
          )}
        </div>
        <CardTitle className="text-sm font-medium leading-tight">{camera.name}</CardTitle>
        <p className="text-xs text-muted-foreground">{camera.label}</p>
      </CardHeader>
      <CardContent className="p-3 pt-0 flex-grow">
        <div className="space-y-1.5 text-xs">
          <div className={`flex items-center gap-1.5 ${connectionColorClass}`}>
            {connectionIcon}
            <span>Connection: {camera.connectionStatus}</span>
          </div>
          <div className={`flex items-center gap-1.5 ${streamColorClass}`}>
            {streamIcon}
            <span>Stream: {camera.streamStatus}</span>
          </div>
        </div>
      </CardContent>
      <CardFooter className="p-3 pt-0">
        <Button
          size="sm"
          variant="outline"
          className="w-full flex items-center gap-1.5 text-xs"
          onClick={() => onTakeSnapshot(camera.id)}
        >
          <CameraIcon className="w-3.5 h-3.5" />
          Take Shot
        </Button>
      </CardFooter>
    </Card>
  )
}

export default CameraCard
